name: Mod Incompatibility ⚠️
description: Report issues caused by using CinematicTools with other mods.
labels: ["compatibility"]
body:
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      placeholder: "e.g. 1.1.0+1.20.4"
    validations:
      required: true

  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: "e.g. 1.20.1"
    validations:
      required: true

  - type: textarea
    id: modlist
    attributes:
      label: Mod List
      placeholder: |
        - superman-mod 1.0.0
        - creativecore 2.9.5
        - ...
      render: text
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Compatibility Issue
      placeholder: "Explain what happens and how it conflicts."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Errors
      description: Paste any related logs or crash info.
      render: text

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      options:
        - label: I tested this with only the conflicting mods and CinematicTools.
        - label: I checked that this issue hasn't been reported yet.
          required: true
